# Generated by Django 5.0.6 on 2024-05-24 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=222, verbose_name='Category name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222, verbose_name='Title')),
                ('about', models.TextField(verbose_name='About')),
                ('price', models.FloatField(validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5), django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('exclusive', models.BooleanField(default=False, verbose_name='Exclusive')),
                ('image', models.ImageField(upload_to='food_images/', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ManyToManyField(to='dingoapp.categorymodel', verbose_name='Category')),
            ],
        ),
    ]
