# Generated by Django 5.0.6 on 2024-05-27 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=222, verbose_name='Full name')),
                ('picture', models.ImageField(upload_to='chefs/', verbose_name='Picture')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('x_twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='X')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('skype', models.URLField(blank=True, max_length=255, null=True, verbose_name='Skype')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dingoapp.cheflevel', verbose_name='Level')),
            ],
        ),
        migrations.AddField(
            model_name='cheflevel',
            name='ch_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dingoapp.chefmodel', verbose_name='Chef level'),
        ),
    ]
