# Generated by Django 5.0.6 on 2024-05-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0002_cheflevel_alter_foodmodel_price_chefmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheflevel',
            name='ch_level',
            field=models.CharField(max_length=222, verbose_name='Chef level'),
        ),
    ]
