# Generated by Django 5.0.6 on 2024-05-28 06:57

import dingoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0005_alter_chefmodel_facebook_alter_chefmodel_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='time',
            field=models.TimeField(validators=[dingoapp.models.past_time_validator], verbose_name='Time'),
        ),
    ]
