# Generated by Django 5.0.6 on 2024-05-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0006_alter_bookingmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='Note',
            new_name='note',
        ),
    ]
