# Generated by Django 5.0.6 on 2024-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0007_rename_note_bookingmodel_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='dingoapp.tagsmodel', verbose_name='Tags'),
        ),
    ]
