# Generated by Django 5.0.6 on 2024-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0008_tagsmodel_foodmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Tag'),
        ),
    ]
