# Generated by Django 5.0.6 on 2024-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0009_alter_tagsmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefmodel',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='skype',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='chefmodel',
            name='x_twitter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='X'),
        ),
    ]
